# Form implementation generated from reading ui file 'login_form_ui.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 700)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(-5, -5, 561, 701))
        self.label_3.setStyleSheet("background: black;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("res/back.jpg"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 450, 650))
        self.widget.setStyleSheet("QWidget {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.00555556 rgba(60, 0, 110, 200), stop:1 rgba(60, 0, 150, 200));\n"
"border-radius: 15px\n"
"}\n"
"\n"
"QPushButton#pushButton {\n"
"    color: black;\n"
"border-radius: 5px;\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(248, 248, 248, 255), stop:1 rgba(207, 207, 207, 255));\n"
"}\n"
"\n"
"QPushButton#pushButton:hover {\n"
"    color: black;\n"
"border-radius: 5px;\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(250, 250, 250, 255));\n"
"transition: .2s;\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed {\n"
"    color: black;\n"
"border-radius: 5px;\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(200, 200, 200, 255));\n"
"padding-left: 15px;\n"
"transition: .2s;\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(150, 85, 150, 150))
        self.label.setStyleSheet("border: #111160 1px solid;\n"
"border-radius: 70px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 80, 151, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setStyleSheet("background: rgba(11, 11, 60, .6);\n"
"padding: 10px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("res/wlt_icn2.png"))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(130, 250, 191, 31))
        self.label_4.setStyleSheet("background: none;\n"
"color: white;\n"
"font: 550 20pt \"Cantarell\";")
        self.label_4.setObjectName("label_4")
        self.login_line = QtWidgets.QLineEdit(parent=self.widget)
        self.login_line.setGeometry(QtCore.QRect(90, 310, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login_line.setFont(font)
        self.login_line.setStyleSheet("background: rgba(0,0,0,0);\n"
"border: none;\n"
"font-family: \"Roboto\";\n"
"background: rgba(11, 11, 31, .2);\n"
"border-radius: 0px;\n"
"border-bottom: 2px solid rgba(200, 200, 200, 255);\n"
"color: rgba(255, 255, 255, 245);\n"
"padding: 5px;\n"
"padding-bottom: 8px;")
        self.login_line.setText("")
        self.login_line.setObjectName("login_line")
        self.password_line = QtWidgets.QLineEdit(parent=self.widget)
        self.password_line.setGeometry(QtCore.QRect(90, 390, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_line.setFont(font)
        self.password_line.setStyleSheet("background: rgba(0,0,0,0);\n"
"border: none;\n"
"background: rgba(11, 11, 31, .2);\n"
"font-family: \"Roboto\";\n"
"border-radius: 0px;\n"
"border-bottom: 2px solid rgba(200, 200, 200, 255);\n"
"color: rgba(255, 255, 255, 245);\n"
"padding: 5px;\n"
"padding-bottom: 8px;")
        self.password_line.setText("")
        self.password_line.setObjectName("password_line")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(90, 500, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Kripton  Wallet"))
        self.login_line.setPlaceholderText(_translate("Dialog", "Login"))
        self.password_line.setPlaceholderText(_translate("Dialog", "Password"))
        self.pushButton.setText(_translate("Dialog", "Log In"))
